plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/MultipleExpectations:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
