# rubocop:disable Metrics/ModuleLength
# frozen_string_literal: true

module Spinel
  module Constants
    NINTENDO_LOGO = %w[
      CE ED 66 66 CC 0D 00 0B 03 73 00 83 00 0C 00 0D
      00 08 11 1F 88 89 00 0E DC CC 6E E6 DD DD D9 99
      BB BB 67 63 6E 0E EC CC DD DC 99 9F BB B9 33 3E
    ].freeze

    # NINTENDO_LOGO_ADDRESSES = (0x0104..0x0133)

    CARTRIDGE_TYPES = {
      '00' => 'ROM ONLY',
      '01' => 'MBC1',
      '02' => 'MBC1+RAM',
      '03' => 'MBC1+RAM+BATTERY',
      '05' => 'MBC2',
      '06' => 'MBC2+BATTERY',
      '08' => 'ROM+RAM',
      '09' => 'ROM+RAM+BATTERY',
      '0B' => 'MMM01',
      '0C' => 'MMM01+RAM',
      '0D' => 'MMM01+RAM+BATTERY',
      '0F' => 'MBC3+TIMER+RAM+BATTERY',
      '10' => 'MBC3+TIMER+RAM+BATTERY',
      '11' => 'MBC3',
      '12' => 'MBC3+RAM',
      '13' => 'MBC3+RAM+BATTERY',
      '19' => 'MBC5',
      '1A' => 'MBC5+RAM',
      '1B' => 'MBC5+RAM+BATTERY',
      '1C' => 'MBC5+RUMBLE',
      '1D' => 'MBC5+RUMBLE+RAM',
      '1E' => 'MBC5+RUMBLE+RAM+BATTERY',
      '20' => 'MBC6',
      '22' => 'MBC7+SENSOR+RUMBLE+RAM+BATTERY',
      'FC' => 'POCKET CAMERA',
      'FD' => 'BANDAI TAMA5',
      'FE' => 'HuC3',
      'FF' => 'HuC1+RAM+BATTERY'
    }.freeze

    ROM_SIZES = {
      '00' => '32 KiB, 2 banks (no banking)',
      '01' => '64 KiB, 4 banks',
      '02' => '128 KiB, 8 banks',
      '03' => '256 KiB, 16 banks',
      '04' => '512 KiB, 32 banks',
      '05' => '1 MiB, 64 banks',
      '06' => '2 MiB, 128 banks',
      '07' => '4 MiB, 256 banks',
      '08' => '8 MiB, 512 banks',
      '52' => '1.1 MiB, 72 banks',
      '53' => '1.2 MiB, 80 banks',
      '54' => '1.5 MiB, 96 banks'
    }.freeze

    RAM_SIZES = {
      '00' => 'No RAM',
      '01' => 'Unused',
      '02' => '8 KiB, 1 bank',
      '03' => '32 KiB, 4 banks of 8 KiB each',
      '04' => '128 KiB, 16 banks of 8 KiB each',
      '05' => '64 KiB, 8 banks of 8 KiB each'
    }.freeze

    OLD_LICENSEE_CODES = {
      '00' => 'None',
      '01' => 'Nintendo',
      '08' => 'Capcom',
      '09' => 'HOT-B',
      '0A' => 'Jaleco',
      '0B' => 'Coconuts Japan',
      '0C' => 'Elite Systems',
      '13' => 'EA (Electronic Arts)',
      '18' => 'Hudson Soft',
      '19' => 'ITC Entertainment',
      '1A' => 'Yanoman',
      '1D' => 'Japan Clary',
      '1F' => 'Virgin Games Ltd.',
      '24' => 'PCM Complete',
      '25' => 'San-X',
      '28' => 'Kemco',
      '29' => 'SETA Corporation',
      '30' => 'Infogrames',
      '31' => 'Nintendo',
      '32' => 'Bandai',
      '33' => 'Indicates that the New licensee code should be used instead.',
      '34' => 'Konami',
      '35' => 'HectorSoft',
      '38' => 'Capcom',
      '39' => 'Banpresto',
      '3C' => 'Entertainment Interactive (stub)',
      '3E' => 'Gremlin',
      '41' => 'Ubi Soft',
      '42' => 'Atlus',
      '44' => 'Malibu Interactive',
      '46' => 'Angel',
      '47' => 'Spectrum HoloByte',
      '49' => 'Irem',
      '4A' => 'Virgin Games Ltd.',
      '4D' => 'Malibu Interactive',
      '4F' => 'U.S. Gold',
      '50' => 'Absolute',
      '51' => 'Acclaim Entertainment',
      '52' => 'Activision',
      '53' => 'Sammy USA Corporation',
      '54' => 'GameTek',
      '55' => 'Park Place',
      '56' => 'LJN',
      '57' => 'Matchbox',
      '59' => 'Milton Bradley Company',
      '5A' => 'Mindscape',
      '5B' => 'Romstar',
      '5C' => 'Naxat Soft',
      '5D' => 'Tradewest',
      '60' => 'Titus Interactive',
      '61' => 'Virgin Games Ltd.',
      '67' => 'Ocean Software',
      '69' => 'EA (Electronic Arts)',
      '6E' => 'Elite Systems',
      '6F' => 'Electro Brain',
      '70' => 'Infogrames',
      '71' => 'Interplay Entertainment',
      '72' => 'Broderbund',
      '73' => 'Sculptured Software',
      '75' => 'The Sales Curve Limited',
      '78' => 'THQ',
      '79' => 'Accolade',
      '7A' => 'Triffix Entertainment',
      '7C' => 'MicroProse',
      '7F' => 'Kemco',
      '80' => 'Misawa Entertainment',
      '83' => 'LOZC G.',
      '86' => 'Tokuma Shoten',
      '8B' => 'Bullet-Proof Software',
      '8C' => 'Vic Tokai Corp.',
      '8E' => 'Ape Inc.',
      '8F' => 'I’Max',
      '91' => 'Chunsoft Co.',
      '92' => 'Video System',
      '93' => 'Tsubaraya Productions',
      '95' => 'Varie',
      '96' => 'Yonezawa/S’Pal',
      '97' => 'Kemco',
      '99' => 'Arc',
      '9A' => 'Nihon Bussan',
      '9B' => 'Tecmo',
      '9C' => 'Imagineer',
      '9D' => 'Banpresto',
      '9F' => 'Nova',
      'A1' => 'Hori Electric',
      'A2' => 'Bandai',
      'A4' => 'Konami',
      'A6' => 'Kawada',
      'A7' => 'Takara',
      'A9' => 'Technos Japan',
      'AA' => 'Broderbund',
      'AC' => 'Toei Animation',
      'AD' => 'Toho',
      'AF' => 'Namco',
      'B0' => 'Acclaim Entertainment',
      'B1' => 'ASCII Corporation or Nexsoft',
      'B2' => 'Bandai',
      'B4' => 'Square Enix',
      'B6' => 'HAL Laboratory',
      'B7' => 'SNK',
      'B9' => 'Pony Canyon',
      'BA' => 'Culture Brain',
      'BB' => 'Sunsoft',
      'BD' => 'Sony Imagesoft',
      'BF' => 'Sammy Corporation',
      'C0' => 'Taito',
      'C2' => 'Kemco',
      'C3' => 'Square',
      'C4' => 'Tokuma Shoten',
      'C5' => 'Data East',
      'C6' => 'Tonkin House',
      'C8' => 'Koei',
      'C9' => 'UFL',
      'CA' => 'Ultra Games',
      'CB' => 'VAP, Inc.',
      'CC' => 'Use Corporation',
      'CD' => 'Meldac',
      'CE' => 'Pony Canyon',
      'CF' => 'Angel',
      'D0' => 'Taito',
      'D1' => 'SOFEL (Software Engineering Lab)',
      'D2' => 'Quest',
      'D3' => 'Sigma Enterprises',
      'D4' => 'ASK Kodansha Co.',
      'D6' => 'Naxat Soft',
      'D7' => 'Copya System',
      'D9' => 'Banpresto',
      'DA' => 'Tomy',
      'DB' => 'LJN',
      'DD' => 'Nippon Computer Systems',
      'DE' => 'Human Ent.',
      'DF' => 'Altron',
      'E0' => 'Jaleco',
      'E1' => 'Towa Chiki',
      'E2' => 'Yutaka # Needs more info',
      'E3' => 'Varie',
      'E5' => 'Epoch',
      'E7' => 'Athena',
      'E8' => 'Asmik Ace Entertainment',
      'E9' => 'Natsume',
      'EA' => 'King Records',
      'EB' => 'Atlus',
      'EC' => 'Epic/Sony Records',
      'EE' => 'IGS',
      'F0' => 'A Wave',
      'F3' => 'Extreme Entertainment',
      'FF' => 'LJN'
    }.freeze
  end
end

# rubocop:enable Metrics/ModuleLength
