module Spinel
  class Rom
    attr_accessor rom_data: Array[Numeric]

    def nintendo_logo: -> String
    def title: -> String
    def manufacturer_code: -> String
    def cgb_flag: -> String
    def licensee_code: -> String
  end
end
